### ISSUE TITLE
Problema integración con votación binaria

### ISSUE THREAD

**Issue by jorsilman** [jorsilman/decide-23#26]
1. Crear una votación de tipo binaria.
2. Parar la votación.
3. Hacer tally a la votación.
4. Visualizar los resultados de la votación.

Se esperan ver los resultados de las votaciones en gráficas diferentes según el tipo de votación. Por consola se muestra un mensaje de que no se le puede aplicar la función map a un tipo null.

Usando la rama jorsilman, en ubuntu.

**Comment by albgalhue** [comment]
Se ha corregido la función de tally para las votaciones de tipo binario, incluyendo el tipo de votacion en 'Mixnet' y los parametros de sus vistas, asi como en el 'models' de las votaciones binarias, con la función de hacer tally.
