### ISSUE TITLE
Ejecutar decide en docker-compose

### ISSUE THREAD

**Issue by jorsilman** [jorsilman/decide-23#60]
Realizar los pasos de la práctica de contenedores para poder ejecutar decide en docker con las nuevas funcioanlidades.

Se espera tener ejecutando decide con los nuevos cambios añadidos en docker.

**Comment by jorsilman** [comment]
Para desplegar decide en docker debemos asegurarnos de que hemos borrado las imagenes y contenedores anteriores, para eso, ejecutamos el comando:
docker system prune -a

Luego, si nos da error en la base de datos por problemas de realaciones o tablas, ejecutamos el siguiente comando:
docker volume prune

Esto lo que hace es eliminar todos los volumenes que tenemos

Por ultimo, no vamos a la carpeta de docker y ejecutamos el comando: docker-compose up

**Comment by fracaralb** [comment]
Hay que tener en cuenta que cuando estamos ejecutando decide en docker, a la hora de crear una nueva votación de cualquier tipo, hay que modificar la **url de auth**. Hay que cambiar la url de _http://localhost:8000/_ por _http://10.5.0.1:8000/_

**Comment by albgalhue** [comment]
Al crear la base de datos desde 0, se necesita crear un super usuario para poder acceder a la aplicación como administrador. 
Para ello ejecutar el comando:
-docker exec -it decide_web python manage.py createsuperuser
Una vez ejecutado seguir los pasos para crear el usuario.
